-- AlterTable
ALTER TABLE "guests" ADD COLUMN IF NOT EXISTS "profileNameChangeCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "guests" ADD COLUMN IF NOT EXISTS "profileNameChangeDay" TEXT;
ALTER TABLE "guests" ADD COLUMN IF NOT EXISTS "profileImageChangeCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "guests" ADD COLUMN IF NOT EXISTS "profileImageChangeDay" TEXT;

-- AlterTable
ALTER TABLE "rooms" ADD COLUMN IF NOT EXISTS "nameChangeCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "rooms" ADD COLUMN IF NOT EXISTS "nameChangeDay" TEXT;
ALTER TABLE "rooms" ADD COLUMN IF NOT EXISTS "imageChangeCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "rooms" ADD COLUMN IF NOT EXISTS "imageChangeDay" TEXT;
